"""Offline export: Markdown travel guides from itinerary data."""

from __future__ import annotations

from typing import Any

from schemas import (
    ItineraryPlan,
    ItineraryRecord,
    TimeSlot,
    UserPreferences,
    daily_budget_allocation,
    day_estimated_cost,
)

_SLOT_EMOJI: dict[TimeSlot, str] = {
    TimeSlot.MORNING: "🌅",
    TimeSlot.LUNCH: "🍽️",
    TimeSlot.AFTERNOON: "🏛️",
    TimeSlot.EVENING: "🌆",
}

_SLOT_ORDER = [TimeSlot.MORNING, TimeSlot.LUNCH, TimeSlot.AFTERNOON, TimeSlot.EVENING]


def _slot_sort_key(slot: TimeSlot) -> int:
    return _SLOT_ORDER.index(slot)


def generate_itinerary_markdown(itinerary_data: dict[str, Any]) -> str:
    """
    Format a full trip as a portable Markdown document.

    Accepts an ``ItineraryRecord``-shaped dict (e.g. from ``model_dump()``).
    """
    record = ItineraryRecord.model_validate(itinerary_data)
    return generate_itinerary_markdown_from_record(record)


def generate_itinerary_markdown_from_record(record: ItineraryRecord) -> str:
    """Format an ``ItineraryRecord`` as Markdown."""
    plan = record.plan
    prefs = record.preferences
    daily_budget = daily_budget_allocation(prefs.budget_tier)
    total_cost = sum(day_estimated_cost(day) for day in plan.days)
    trip_budget = daily_budget * plan.duration_days

    lines: list[str] = [
        f"# ✈️ Itinera Travel Guide — {plan.destination}",
        "",
        "> Offline itinerary · safe to save on your phone",
        "",
        "## 📋 Trip overview",
        "",
        f"| Detail | Value |",
        f"|--------|-------|",
        f"| **Destination** | {plan.destination} |",
        f"| **Duration** | {plan.duration_days} days |",
        f"| **Travel party** | {prefs.travel_party.value} |",
        f"| **Pace** | {prefs.pace.value} |",
        f"| **Budget tier** | {prefs.budget_tier.value} |",
        f"| **Interests** | {', '.join(i.value for i in prefs.interests)} |",
        f"| **Daily budget guide** | ${daily_budget:,.0f}/day |",
        f"| **Est. total spend** | ${total_cost:,.0f} (vs ${trip_budget:,.0f} tier guide) |",
        f"| **Itinerary ID** | `{record.itinerary_id}` |",
        "",
    ]

    for day in plan.days:
        day_cost = day_estimated_cost(day)
        burn_pct = (day_cost / daily_budget * 100) if daily_budget else 0
        lines.extend(
            [
                f"## 📅 Day {day.day_number}",
                "",
                f"**Daily spend:** ${day_cost:,.0f} · **Burn rate:** {burn_pct:.0f}% of ${daily_budget:,.0f} guide",
                "",
            ]
        )

        sorted_blocks = sorted(day.time_blocks, key=lambda b: _slot_sort_key(b.time_slot))
        for stop_num, block in enumerate(sorted_blocks, start=1):
            activity = block.activity
            emoji = _SLOT_EMOJI.get(block.time_slot, "📍")
            verify_line = (
                f"✅ **Verified address:** {activity.formatted_address}"
                if activity.is_verified and activity.formatted_address
                else "⚠️ **Location estimated** — double-check venue status before visiting."
            )

            source_line = (
                f"- 🔗 **Source:** {activity.source_hint}"
                if activity.source_hint
                else ""
            )
            lines.extend(
                [
                    f"### {emoji} Stop {stop_num} — {block.time_slot.value}",
                    "",
                    f"#### {activity.activity_name}",
                    "",
                    f"- 💵 **Est. cost:** ${activity.estimated_cost:,.0f}",
                    f"- 📍 **Coordinates:** `{activity.latitude:.5f}, {activity.longitude:.5f}`",
                    f"- {verify_line}",
                ]
            )
            if source_line:
                lines.append(source_line)
            if activity.is_live_event:
                lines.append("- 🎫 **Live event** (concert, sports, theater, or match day)")
            lines.extend(["", activity.description, "", "---", ""])

    lines.extend(
        [
            "## 🗺️ Route notes",
            "",
            "Stops are ordered **Morning → Lunch → Afternoon → Evening** each day.",
            "Follow the sequence for the most efficient walking route.",
            "",
            "---",
            "",
            "*Generated by [Itinera](https://github.com/hamidmatiny/Itinera) · xAI Grok + OpenStreetMap verification*",
        ]
    )

    return "\n".join(lines)


def record_to_export_dict(record: ItineraryRecord) -> dict[str, Any]:
    """Serialize a record for export APIs."""
    return record.model_dump(mode="json")


def plan_and_preferences_to_markdown(
    plan: ItineraryPlan,
    preferences: UserPreferences,
    itinerary_id: str,
    *,
    created_at: str = "",
) -> str:
    """Build Markdown from plan + preferences without a full DB record."""
    record = ItineraryRecord(
        itinerary_id=itinerary_id,
        preferences=preferences,
        plan=plan,
        created_at=created_at or "—",
    )
    return generate_itinerary_markdown_from_record(record)
